version: "3.8"

services:
  app:
    container_name: binance-volume-chart
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/collector",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    # This allows the container to handle system signals properly
    stop_signal: SIGINT
    stop_grace_period: 30s
