version: "3.8"

services:
  app:
    container_name: binance-volume-chart
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - REDIS_URL=redis://localhost:6379
    # The healthcheck is now defined in the Dockerfile
    # This allows the container to handle system signals properly
    stop_signal: SIGINT
    stop_grace_period: 30s
